language: python

python:
  - "3.6"

install:
  - pip install codecov

script:
  - coverage run tests.py

after_success:
  - codecov run helloWorld.py
  - codecov --token=db371fc3-d78a-426f-8efe-727db92dfa6d

#script:
#  - python helloWorld.py

notifications:
  email: false
