version: "2"
services:
  web:
    build: .
    ports:
      - "7001:7001"
    links:
      - mongo
    environment:
      MONGO_URI: mongodb://localhost:27017/query-server
  mongo:
    image: mongo:latest@sha256:07212fb304ea36b8c5a9e5694527f16deeb0b99f87fc60162dc15ab260bf8a2a
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
