version: "2"
services:
  web:
    build: .
    ports:
      - "7001:7001"
    links:
      - mongo
    environment:
      MONGO_URI: mongodb://localhost:27017/query-server
  mongo:
    image: mongo:latest@sha256:c6d2b2f8c054210db26b492bab81ffab171ee54eb58925fa98fabb4faca3a9cb
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
