version: "2"
services:
  web:
    build: .
    ports:
      - "7001:7001"
    links:
      - mongo
    environment:
      MONGO_URI: mongodb://localhost:27017/query-server
  mongo:
    image: mongo:latest@sha256:c4e8225e68348b18283cf5c523f99122426fe1e15d883104e24c61bedb4b2ca7
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
